// Copyright 2023 Anlity <leo@leocode.net>. All rights reserved.
// Use of this source code is governed by a AGPL v3.0 style
// license that can be found in the LICENSE file.

// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// ConfigWalletDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type ConfigWalletDao struct {
	gmvc.M                      // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB              // DB is the raw underlying database management object.
	Table   string              // Table is the table name of the DAO.
	Columns configWalletColumns // Columns contains all the columns of Table that for convenient usage.
}

// ConfigWalletColumns defines and stores column names for table c_config_wallet.
type configWalletColumns struct {
	Field      string // 钱包字段名
	WalletName string // 钱包名称
}

func NewConfigWalletDao() *ConfigWalletDao {
	return &ConfigWalletDao{
		M:     g.DB("default").Model("c_config_wallet").Safe(),
		DB:    g.DB("default"),
		Table: "c_config_wallet",
		Columns: configWalletColumns{
			Field:      "field",
			WalletName: "wallet_name",
		},
	}
}
