// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// ConfigSensitiveWordDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type ConfigSensitiveWordDao struct {
	gmvc.M                             // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB                     // DB is the raw underlying database management object.
	Table   string                     // Table is the table name of the DAO.
	Columns configSensitiveWordColumns // Columns contains all the columns of Table that for convenient usage.
}

// ConfigSensitiveWordColumns defines and stores column names for table c_config_sensitive_word.
type configSensitiveWordColumns struct {
	Id        string // ID
	Content   string // 敏感词内容
	CreatedAt string // 创建时间
}

func NewConfigSensitiveWordDao() *ConfigSensitiveWordDao {
	return &ConfigSensitiveWordDao{
		M:     g.DB("default").Model("c_config_sensitive_word").Safe(),
		DB:    g.DB("default"),
		Table: "c_config_sensitive_word",
		Columns: configSensitiveWordColumns{
			Id:        "id",
			Content:   "content",
			CreatedAt: "created_at",
		},
	}
}
