// Copyright 2023 Anlity <leo@leocode.net>. All rights reserved.
// Use of this source code is governed by a AGPL v3.0 style
// license that can be found in the LICENSE file.

// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// DomainCertFlowDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type DomainCertFlowDao struct {
	gmvc.M                        // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB                // DB is the raw underlying database management object.
	Table   string                // Table is the table name of the DAO.
	Columns domainCertFlowColumns // Columns contains all the columns of Table that for convenient usage.
}

// DomainCertFlowColumns defines and stores column names for table c_domain_cert_flow.
type domainCertFlowColumns struct {
	Id             string // id
	CertKey        string // 证书
	OldExpireDate  string // 原有效期
	NewExpireDate  string // 更新后的有效期
	OldCertContent string // 原证书内容
	NewCertContent string // 更新后的证书内容
	CreatedAt      string // 创建时间
}

func NewDomainCertFlowDao() *DomainCertFlowDao {
	return &DomainCertFlowDao{
		M:     g.DB("default").Model("c_domain_cert_flow").Safe(),
		DB:    g.DB("default"),
		Table: "c_domain_cert_flow",
		Columns: domainCertFlowColumns{
			Id:             "id",
			CertKey:        "cert_key",
			OldExpireDate:  "old_expire_date",
			NewExpireDate:  "new_expire_date",
			OldCertContent: "old_cert_content",
			NewCertContent: "new_cert_content",
			CreatedAt:      "created_at",
		},
	}
}
