// Copyright 2023 Anlity <leo@leocode.net>. All rights reserved.
// Use of this source code is governed by a AGPL v3.0 style
// license that can be found in the LICENSE file.

// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// HandOutErrorFlowDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type HandOutErrorFlowDao struct {
	gmvc.M                          // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB                  // DB is the raw underlying database management object.
	Table   string                  // Table is the table name of the DAO.
	Columns handOutErrorFlowColumns // Columns contains all the columns of Table that for convenient usage.
}

// HandOutErrorFlowColumns defines and stores column names for table c_hand_out_error_flow.
type handOutErrorFlowColumns struct {
	Id        string // id
	UserId    string // 会员ID
	LevelId   string // 会员级别
	ErrorData string // 错误内容
	CreatedAt string // 创建时间
}

func NewHandOutErrorFlowDao() *HandOutErrorFlowDao {
	return &HandOutErrorFlowDao{
		M:     g.DB("default").Model("c_hand_out_error_flow").Safe(),
		DB:    g.DB("default"),
		Table: "c_hand_out_error_flow",
		Columns: handOutErrorFlowColumns{
			Id:        "id",
			UserId:    "user_id",
			LevelId:   "level_id",
			ErrorData: "error_data",
			CreatedAt: "created_at",
		},
	}
}
