// Copyright 2023 Anlity <leo@leocode.net>. All rights reserved.
// Use of this source code is governed by a AGPL v3.0 style
// license that can be found in the LICENSE file.

// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// ShopOrderGoodsDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type ShopOrderGoodsDao struct {
	gmvc.M                        // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB                // DB is the raw underlying database management object.
	Table   string                // Table is the table name of the DAO.
	Columns shopOrderGoodsColumns // Columns contains all the columns of Table that for convenient usage.
}

// ShopOrderGoodsColumns defines and stores column names for table c_shop_order_goods.
type shopOrderGoodsColumns struct {
	Id            string // ID
	OrderId       string // 订单ID
	UserId        string // 会员ID
	GoodsId       string // 商品ID
	GoodsNum      string // 商品数量
	GoodsSnapshot string // 商品快照
	CreatedAt     string // 创建时间
	UpdatedAt     string // 更新时间
}

func NewShopOrderGoodsDao() *ShopOrderGoodsDao {
	return &ShopOrderGoodsDao{
		M:     g.DB("default").Model("c_shop_order_goods").Safe(),
		DB:    g.DB("default"),
		Table: "c_shop_order_goods",
		Columns: shopOrderGoodsColumns{
			Id:            "id",
			OrderId:       "order_id",
			UserId:        "user_id",
			GoodsId:       "goods_id",
			GoodsNum:      "goods_num",
			GoodsSnapshot: "goods_snapshot",
			CreatedAt:     "created_at",
			UpdatedAt:     "updated_at",
		},
	}
}
