// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// UserSensitiveWordDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type UserSensitiveWordDao struct {
	gmvc.M                           // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB                   // DB is the raw underlying database management object.
	Table   string                   // Table is the table name of the DAO.
	Columns userSensitiveWordColumns // Columns contains all the columns of Table that for convenient usage.
}

// UserSensitiveWordColumns defines and stores column names for table c_user_sensitive_word.
type userSensitiveWordColumns struct {
	Id             string // ID
	UserId         string // 会员ID
	Type           string // 类型: 1对话 2用户名
	TopicType      string // 对话类型: 0无 1gpt3 2gpt4 3mj
	Content        string // 触发敏感词原文
	ValidateResult string // 敏感词json
	CreatedAt      string // 创建时间
}

func NewUserSensitiveWordDao() *UserSensitiveWordDao {
	return &UserSensitiveWordDao{
		M:     g.DB("default").Model("c_user_sensitive_word").Safe(),
		DB:    g.DB("default"),
		Table: "c_user_sensitive_word",
		Columns: userSensitiveWordColumns{
			Id:             "id",
			UserId:         "user_id",
			Type:           "type",
			TopicType:      "topic_type",
			Content:        "content",
			ValidateResult: "validate_result",
			CreatedAt:      "created_at",
		},
	}
}
