// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/anlityli/chatait-free/chatait-public-lib/app/dao/internal"
)

// configSensitiveWordDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type configSensitiveWordDao struct {
	*internal.ConfigSensitiveWordDao
}

var (
	// ConfigSensitiveWord is globally public accessible object for table c_config_sensitive_word operations.
	ConfigSensitiveWord configSensitiveWordDao
)

func init() {
	ConfigSensitiveWord = configSensitiveWordDao{
		internal.NewConfigSensitiveWordDao(),
	}
}

// Fill with you ideas below.
