// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/anlityli/chatait-free/chatait-public-lib/app/dao/internal"
)

// configBaiduDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type configBaiduDao struct {
	*internal.ConfigBaiduDao
}

var (
	// ConfigBaidu is globally public accessible object for table c_config_baidu operations.
	ConfigBaidu configBaiduDao
)

func init() {
	ConfigBaidu = configBaiduDao{
		internal.NewConfigBaiduDao(),
	}
}

// Fill with you ideas below.
