// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/anlityli/chatait-free/chatait-public-lib/app/dao/internal"
)

// userSensitiveWordDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type userSensitiveWordDao struct {
	*internal.UserSensitiveWordDao
}

var (
	// UserSensitiveWord is globally public accessible object for table c_user_sensitive_word operations.
	UserSensitiveWord userSensitiveWordDao
)

func init() {
	UserSensitiveWord = userSensitiveWordDao{
		internal.NewUserSensitiveWordDao(),
	}
}

// Fill with you ideas below.
