// Copyright 2023 Anlity <leo@leocode.net>. All rights reserved.
// Use of this source code is governed by a AGPL v3.0 style
// license that can be found in the LICENSE file.

// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// Admin is the golang structure for table c_admin.
type Admin struct {
	Id                 int64  `orm:"id,primary"           json:"id"`                 //
	UserId             int64  `orm:"user_id"              json:"userId"`             // 前台会员ID
	AdminName          string `orm:"admin_name"           json:"adminName"`          // 管理员名
	RealName           string `orm:"real_name"            json:"realName"`           // 真实姓名
	Remark             string `orm:"remark"               json:"remark"`             // 备注
	RoleId             int64  `orm:"role_id"              json:"roleId"`             // 角色ID
	IsEnable           uint   `orm:"is_enable"            json:"isEnable"`           // 是否启用
	AuthKey            string `orm:"auth_key"             json:"authKey"`            // 授权key
	PasswordHash       string `orm:"password_hash"        json:"passwordHash"`       // hash密码
	PasswordResetToken string `orm:"password_reset_token" json:"passwordResetToken"` //
	DontDel            uint   `orm:"dont_del"             json:"dontDel"`            // 是否允许删除
	LoginNums          uint   `orm:"login_nums"           json:"loginNums"`          // 登陆次数
	FailNums           uint   `orm:"fail_nums"            json:"failNums"`           // 失败次数
	LastLoginIp        string `orm:"last_login_ip"        json:"lastLoginIp"`        // 最后登录IP
	LastLoginAt        uint   `orm:"last_login_at"        json:"lastLoginAt"`        // 最后登录时间
	BindIp             string `orm:"bind_ip"              json:"bindIp"`             // 绑定IP
	CreateAdmin        string `orm:"create_admin"         json:"createAdmin"`        // 创建管理员ID
	UpdateAdmin        string `orm:"update_admin"         json:"updateAdmin"`        // 更新管理员ID
	CreatedAt          uint   `orm:"created_at"           json:"createdAt"`          // 创建时间
	UpdatedAt          uint   `orm:"updated_at"           json:"updatedAt"`          // 更新时间
	IsDelete           uint   `orm:"is_delete"            json:"isDelete"`           // 是否删除
	DeletedAt          uint   `orm:"deleted_at"           json:"deletedAt"`          // 删除时间
}
