// Copyright 2023 Anlity <leo@leocode.net>. All rights reserved.
// Use of this source code is governed by a AGPL v3.0 style
// license that can be found in the LICENSE file.

// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// AdminRole is the golang structure for table c_admin_role.
type AdminRole struct {
	Id               uint64 `orm:"id,primary"        json:"id"`               //
	RoleName         string `orm:"role_name"         json:"roleName"`         // 角色名
	Remark           string `orm:"remark"            json:"remark"`           // 备注
	Permission       string `orm:"permission"        json:"permission"`       // 权限
	ColumnPermission string `orm:"column_permission" json:"columnPermission"` // 字段权限
	DontDel          uint   `orm:"dont_del"          json:"dontDel"`          // 不允许删除
	CreateAdmin      string `orm:"create_admin"      json:"createAdmin"`      // 创建管理员ID
	UpdateAdmin      string `orm:"update_admin"      json:"updateAdmin"`      // 更新管理员ID
	CreatedAt        uint   `orm:"created_at"        json:"createdAt"`        // 创建时间
	UpdatedAt        uint   `orm:"updated_at"        json:"updatedAt"`        // 更新时间
}
