// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// ConfigBaidu is the golang structure for table c_config_baidu.
type ConfigBaidu struct {
	Id        int64  `orm:"id,primary" json:"id"`        // ID
	Title     string `orm:"title"      json:"title"`     // 标题
	ApiKey    string `orm:"api_key"    json:"apiKey"`    //
	SecretKey string `orm:"secret_key" json:"secretKey"` //
	Status    int    `orm:"status"     json:"status"`    // 启用状态
	CallNum   int    `orm:"call_num"   json:"callNum"`   // 调用次数
	CreatedAt int    `orm:"created_at" json:"createdAt"` // 创建时间
	UpdatedAt int    `orm:"updated_at" json:"updatedAt"` // 更新时间
}
