// Copyright 2023 Anlity <leo@leocode.net>. All rights reserved.
// Use of this source code is governed by a AGPL v3.0 style
// license that can be found in the LICENSE file.

// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// ConfigLevel is the golang structure for table c_config_level.
type ConfigLevel struct {
	Id              int    `orm:"id,primary"       json:"id"`              // ID
	LevelName       string `orm:"level_name"       json:"levelName"`       // 级别名称
	MonthGpt3       int    `orm:"month_gpt3"       json:"monthGpt3"`       // 月赠送gpt3次数
	MonthGpt4       int    `orm:"month_gpt4"       json:"monthGpt4"`       // 月赠送gpt4次数
	MonthMidjourney int    `orm:"month_midjourney" json:"monthMidjourney"` // 月赠送midjourney次数
}
