// Copyright 2023 Anlity <leo@leocode.net>. All rights reserved.
// Use of this source code is governed by a AGPL v3.0 style
// license that can be found in the LICENSE file.

// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// ConfigWallet is the golang structure for table c_config_wallet.
type ConfigWallet struct {
	Field      string `orm:"field,primary" json:"field"`      // 钱包字段名
	WalletName string `orm:"wallet_name"   json:"walletName"` // 钱包名称
}
