// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// ConfigOpenai is the golang structure for table c_config_openai.
type ConfigOpenai struct {
	Id        int64  `orm:"id,primary" json:"id"`        // ID
	Title     string `orm:"title"      json:"title"`     // 标题
	ApiUrl    string `orm:"api_url"    json:"apiUrl"`    // 接口地址
	ApiKey    string `orm:"api_key"    json:"apiKey"`    // api_key
	Proxy     string `orm:"proxy"      json:"proxy"`     // 代理地址
	MaxTokens int    `orm:"max_tokens" json:"maxTokens"` // 最大Token
	Status    int    `orm:"status"     json:"status"`    // 是否启用 1启用 0不启用
	CallNum   int    `orm:"call_num"   json:"callNum"`   // 接口调用次数
	CreatedAt int    `orm:"created_at" json:"createdAt"` // 创建时间
	UpdatedAt int    `orm:"updated_at" json:"updatedAt"` // 更新时间
}
