// Copyright 2023 Anlity <leo@leocode.net>. All rights reserved.
// Use of this source code is governed by a AGPL v3.0 style
// license that can be found in the LICENSE file.

// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// ConfigMidjourney is the golang structure for table c_config_midjourney.
type ConfigMidjourney struct {
	Id               int64  `orm:"id,primary"         json:"id"`               // ID
	Title            string `orm:"title"              json:"title"`            // 标题
	GuildId          string `orm:"guild_id"           json:"guildId"`          // 服务ID
	ChannelId        string `orm:"channel_id"         json:"channelId"`        // 频道ID
	UserToken        string `orm:"user_token"         json:"userToken"`        // 用户Token
	MjBotId          string `orm:"mj_bot_id"          json:"mjBotId"`          // midjourney的BotId
	BotToken         string `orm:"bot_token"          json:"botToken"`         // 自己的BotToken
	SessionId        string `orm:"session_id"         json:"sessionId"`        // SessionID
	UserAgent        string `orm:"user_agent"         json:"userAgent"`        // UserAgent
	HuggingFaceToken string `orm:"hugging_face_token" json:"huggingFaceToken"` // HuggingFaceToken
	Proxy            string `orm:"proxy"              json:"proxy"`            // 代理地址
	Status           int    `orm:"status"             json:"status"`           // 是否启用 1启用 0不启用
	ListenModel      int    `orm:"listen_model"       json:"listenModel"`      // 监听模式 1userWss 0bot
	CreateModel      string `orm:"create_model"       json:"createModel"`      // 生成图的模式 fast relax turbo
	WsIdleTime       int    `orm:"ws_idle_time"       json:"wsIdleTime"`       // websocket闲置时间秒数
	CallNum          int    `orm:"call_num"           json:"callNum"`          // 接口调用次数
	CreatedAt        int    `orm:"created_at"         json:"createdAt"`        // 创建时间
	UpdatedAt        int    `orm:"updated_at"         json:"updatedAt"`        // 更新时间
}
