// Copyright 2023 Anlity <leo@leocode.net>. All rights reserved.
// Use of this source code is governed by a AGPL v3.0 style
// license that can be found in the LICENSE file.

// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// ConfigPay is the golang structure for table c_config_pay.
type ConfigPay struct {
	Id                  int    `orm:"id,primary"           json:"id"`                  // ID
	ApiName             string `orm:"api_name"             json:"apiName"`             // 支付方式名称
	Params              string `orm:"params"               json:"params"`              // 配置参数json
	PayChannel          string `orm:"pay_channel"          json:"payChannel"`          // 支付渠道的配置json
	FrontendDescription string `orm:"frontend_description" json:"frontendDescription"` // 支付方式描述
	BackendDescription  string `orm:"backend_description"  json:"backendDescription"`  // 支付方式后台描述
	Status              int    `orm:"status"               json:"status"`              // 状态
	CreatedAt           int    `orm:"created_at"           json:"createdAt"`           // 创建时间
	UpdatedAt           int    `orm:"updated_at"           json:"updatedAt"`           // 更新时间
}
