// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// ConfigSensitiveWord is the golang structure for table c_config_sensitive_word.
type ConfigSensitiveWord struct {
	Id        int64  `orm:"id,primary" json:"id"`        // ID
	Content   string `orm:"content"    json:"content"`   // 敏感词内容
	CreatedAt int    `orm:"created_at" json:"createdAt"` // 创建时间
}
