// Copyright 2023 Anlity <leo@leocode.net>. All rights reserved.
// Use of this source code is governed by a AGPL v3.0 style
// license that can be found in the LICENSE file.

// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// Conversation is the golang structure for table c_conversation.
type Conversation struct {
	Id        int64  `orm:"id,primary" json:"id"`        // ID
	UserId    int64  `orm:"user_id"    json:"userId"`    // 会员ID
	TopicId   int64  `orm:"topic_id"   json:"topicId"`   // 话题
	Role      string `orm:"role"       json:"role"`      // 对话角色
	Content   string `orm:"content"    json:"content"`   // 对话内容
	CreatedAt int    `orm:"created_at" json:"createdAt"` // 创建时间
	UpdatedAt int    `orm:"updated_at" json:"updatedAt"` // 更新时间
}
