// Copyright 2023 Anlity <leo@leocode.net>. All rights reserved.
// Use of this source code is governed by a AGPL v3.0 style
// license that can be found in the LICENSE file.

// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// DomainCert is the golang structure for table c_domain_cert.
type DomainCert struct {
	CertKey     string      `orm:"cert_key,primary" json:"certKey"`     // cert_key
	Domains     string      `orm:"domains"          json:"domains"`     // 域名逗号分隔
	ExpireDate  *gtime.Time `orm:"expire_date"      json:"expireDate"`  // 有效日期
	CertContent string      `orm:"cert_content"     json:"certContent"` // 证书内容
	IsBan       int         `orm:"is_ban"           json:"isBan"`       // 是否被禁用
	BanReason   string      `orm:"ban_reason"       json:"banReason"`   // 禁用原因
	CallNum     int         `orm:"call_num"         json:"callNum"`     // 接口被请求次数
	CreatedAt   int         `orm:"created_at"       json:"createdAt"`   // 创建时间
	UpdatedAt   int         `orm:"updated_at"       json:"updatedAt"`   // 更新时间
}
