// Copyright 2023 Anlity <leo@leocode.net>. All rights reserved.
// Use of this source code is governed by a AGPL v3.0 style
// license that can be found in the LICENSE file.

// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// DomainCertFlow is the golang structure for table c_domain_cert_flow.
type DomainCertFlow struct {
	Id             int64       `orm:"id,primary"       json:"id"`             // id
	CertKey        string      `orm:"cert_key"         json:"certKey"`        // 证书
	OldExpireDate  *gtime.Time `orm:"old_expire_date"  json:"oldExpireDate"`  // 原有效期
	NewExpireDate  *gtime.Time `orm:"new_expire_date"  json:"newExpireDate"`  // 更新后的有效期
	OldCertContent string      `orm:"old_cert_content" json:"oldCertContent"` // 原证书内容
	NewCertContent string      `orm:"new_cert_content" json:"newCertContent"` // 更新后的证书内容
	CreatedAt      int         `orm:"created_at"       json:"createdAt"`      // 创建时间
}
