// Copyright 2023 Anlity <leo@leocode.net>. All rights reserved.
// Use of this source code is governed by a AGPL v3.0 style
// license that can be found in the LICENSE file.

// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// EmailCode is the golang structure for table c_email_code.
type EmailCode struct {
	Id            int64  `orm:"id,primary"     json:"id"`            // ID
	Email         string `orm:"email,unique"   json:"email"`         // 邮箱
	Ip            string `orm:"ip"             json:"ip"`            // IP
	Scenario      string `orm:"scenario"       json:"scenario"`      // 场景
	Code          string `orm:"code"           json:"code"`          // 验证码
	ValidateTimes int    `orm:"validate_times" json:"validateTimes"` // 校验次数
	CreatedAt     int    `orm:"created_at"     json:"createdAt"`     // 创建时间
	UpdatedAt     int    `orm:"updated_at"     json:"updatedAt"`     // 更新时间
}
