// Copyright 2023 Anlity <leo@leocode.net>. All rights reserved.
// Use of this source code is governed by a AGPL v3.0 style
// license that can be found in the LICENSE file.

// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// HandOutErrorFlow is the golang structure for table c_hand_out_error_flow.
type HandOutErrorFlow struct {
	Id        int64  `orm:"id,primary" json:"id"`        // id
	UserId    int64  `orm:"user_id"    json:"userId"`    // 会员ID
	LevelId   int    `orm:"level_id"   json:"levelId"`   // 会员级别
	ErrorData string `orm:"error_data" json:"errorData"` // 错误内容
	CreatedAt int    `orm:"created_at" json:"createdAt"` // 创建时间
}
