// Copyright 2023 Anlity <leo@leocode.net>. All rights reserved.
// Use of this source code is governed by a AGPL v3.0 style
// license that can be found in the LICENSE file.

// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// PayFlow is the golang structure for table c_pay_flow.
type PayFlow struct {
	Id                int64  `orm:"id,primary"          json:"id"`                // ID
	FlowType          int    `orm:"flow_type"           json:"flowType"`          // 记录类型 1商城订单
	TargetId          int64  `orm:"target_id"           json:"targetId"`          // 目标ID
	ConfigPayId       int    `orm:"config_pay_id"       json:"configPayId"`       // 支付接口ID
	PayChannel        string `orm:"pay_channel"         json:"payChannel"`        // 支付渠道以支付接口为准
	OrderAmount       int    `orm:"order_amount"        json:"orderAmount"`       // 订单原金额
	PayAmount         int    `orm:"pay_amount"          json:"payAmount"`         // 实付金额
	Status            int    `orm:"status"              json:"status"`            // 状态 0已创建 1已支付 2支付失败 3已过期
	PaymentResponse   string `orm:"payment_response"    json:"paymentResponse"`   // 调用接口返回内容
	PaymentFailReason string `orm:"payment_fail_reason" json:"paymentFailReason"` // 调用接口失败原因
	NotifyResponse    string `orm:"notify_response"     json:"notifyResponse"`    // 接口回调原文
	NotifyFailReason  string `orm:"notify_fail_reason"  json:"notifyFailReason"`  // 回调失败原因
	CreatedAt         int    `orm:"created_at"          json:"createdAt"`         // 创建时间
	UpdatedAt         int    `orm:"updated_at"          json:"updatedAt"`         // 更新时间
	PaidAt            int    `orm:"paid_at"             json:"paidAt"`            // 支付时间
	DueExpireAt       int    `orm:"due_expire_at"       json:"dueExpireAt"`       // 应到期时间
	ExpiredAt         int    `orm:"expired_at"          json:"expiredAt"`         // 过期时间
}
