// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// QueueMidjourney is the golang structure for table c_queue_midjourney.
type QueueMidjourney struct {
	Id              int64  `orm:"id,primary"       json:"id"`              // ID
	ConversationId  int64  `orm:"conversation_id"  json:"conversationId"`  // 对话ID
	ConfigId        int64  `orm:"config_id"        json:"configId"`        // 接口配置ID
	ActionType      int    `orm:"action_type"      json:"actionType"`      // 行为类型  1生图 2Upscale
	ApplicationType int    `orm:"application_type" json:"applicationType"` // 应用机器人类型 1MJ 2Niji
	Nonce           int64  `orm:"nonce"            json:"nonce"`           // nonceID
	MessageId       int64  `orm:"message_id"       json:"messageId"`       // 消息结束ID(生成图片完成时的消息ID)
	ReferMessageId  int64  `orm:"refer_message_id" json:"referMessageId"`  // 提到的消息ID(生图动作为0)
	InteractionId   int64  `orm:"interaction_id"   json:"interactionId"`   // 交互ID
	ReferIndex      int    `orm:"refer_index"      json:"referIndex"`      // 处理提到的消息的索引
	MessageHash     string `orm:"message_hash"     json:"messageHash"`     // 消息hash
	MessageType     int    `orm:"message_type"     json:"messageType"`     // 消息type
	MessageContent  string `orm:"message_content"  json:"messageContent"`  // 消息内容(提示词内容用于匹配任务)
	RequestType     int    `orm:"request_type"     json:"requestType"`     // 请求消息时用到的类型 2生图 3Upscale 3variation
	RequestUrl      string `orm:"request_url"      json:"requestUrl"`      // 请求接口的url
	RequestData     string `orm:"request_data"     json:"requestData"`     // 请求接口的数据内容
	ResponseData    string `orm:"response_data"    json:"responseData"`    // 接口返回的数据内容
	ErrorData       string `orm:"error_data"       json:"errorData"`       // 错误数据内容
	Status          int    `orm:"status"           json:"status"`          // 状态 0任务进入队列 1 任务开始 2任务正常结束 3任务出错
	Progress        int    `orm:"progress"         json:"progress"`        // 任务执行进度
	CreatedAt       int    `orm:"created_at"       json:"createdAt"`       // 创建时间
	StartedAt       int    `orm:"started_at"       json:"startedAt"`       // 任务开始时间
	EndedAt         int    `orm:"ended_at"         json:"endedAt"`         // 任务结束时间
	ErrorAt         int    `orm:"error_at"         json:"errorAt"`         // 任务发生错误时间
}
