// Copyright 2023 Anlity <leo@leocode.net>. All rights reserved.
// Use of this source code is governed by a AGPL v3.0 style
// license that can be found in the LICENSE file.

// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// ShopOrderGoods is the golang structure for table c_shop_order_goods.
type ShopOrderGoods struct {
	Id            int64  `orm:"id,primary"     json:"id"`            // ID
	OrderId       int64  `orm:"order_id"       json:"orderId"`       // 订单ID
	UserId        int64  `orm:"user_id"        json:"userId"`        // 会员ID
	GoodsId       int64  `orm:"goods_id"       json:"goodsId"`       // 商品ID
	GoodsNum      int    `orm:"goods_num"      json:"goodsNum"`      // 商品数量
	GoodsSnapshot string `orm:"goods_snapshot" json:"goodsSnapshot"` // 商品快照
	CreatedAt     int    `orm:"created_at"     json:"createdAt"`     // 创建时间
	UpdatedAt     int    `orm:"updated_at"     json:"updatedAt"`     // 更新时间
}
