// Copyright 2023 Anlity <leo@leocode.net>. All rights reserved.
// Use of this source code is governed by a AGPL v3.0 style
// license that can be found in the LICENSE file.

// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// ShopOrder is the golang structure for table c_shop_order.
type ShopOrder struct {
	Id          int64  `orm:"id,primary"      json:"id"`          // ID
	OrderSn     string `orm:"order_sn,unique" json:"orderSn"`     // 订单编号
	UserId      int64  `orm:"user_id"         json:"userId"`      // 会员ID
	OrderAmount int    `orm:"order_amount"    json:"orderAmount"` // 订单金额
	PayAmount   int    `orm:"pay_amount"      json:"payAmount"`   // 实付金额
	Status      int    `orm:"status"          json:"status"`      // 状态 0创建 1已支付 2已发货 3已收货 4已完成 9已取消
	CreatedAt   int    `orm:"created_at"      json:"createdAt"`   // 创建时间
	UpdatedAt   int    `orm:"updated_at"      json:"updatedAt"`   // 更新时间
	PaidAt      int    `orm:"paid_at"         json:"paidAt"`      // 支付时间
	DueExpireAt int    `orm:"due_expire_at"   json:"dueExpireAt"` // 应过期时间
	ExpiredAt   int    `orm:"expired_at"      json:"expiredAt"`   // 过期时间
}
