// Copyright 2023 Anlity <leo@leocode.net>. All rights reserved.
// Use of this source code is governed by a AGPL v3.0 style
// license that can be found in the LICENSE file.

// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// Topic is the golang structure for table c_topic.
type Topic struct {
	Id        int64  `orm:"id,primary" json:"id"`        // ID
	UserId    int64  `orm:"user_id"    json:"userId"`    // 会员ID
	Title     string `orm:"title"      json:"title"`     // 话题标题
	Type      int    `orm:"type"       json:"type"`      // 话题类型 1:gpt3.5 2:gpt4 3:midjourney
	CreatedAt int    `orm:"created_at" json:"createdAt"` // 创建时间
	UpdatedAt int    `orm:"updated_at" json:"updatedAt"` // 更新时间
}
