// Copyright 2023 Anlity <leo@leocode.net>. All rights reserved.
// Use of this source code is governed by a AGPL v3.0 style
// license that can be found in the LICENSE file.

// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// User is the golang structure for table c_user.
type User struct {
	Id               int64       `orm:"id,primary"         json:"id"`               // ID
	Username         string      `orm:"username,unique"    json:"username"`         // 用户名
	Password         string      `orm:"password"           json:"password"`         // 密码
	LevelId          int         `orm:"level_id"           json:"levelId"`          // 级别ID
	LevelExpireDate  *gtime.Time `orm:"level_expire_date"  json:"levelExpireDate"`  // 级别到期日期
	LevelExpireYear  int         `orm:"level_expire_year"  json:"levelExpireYear"`  // 级别到期日期年
	LevelExpireMonth int         `orm:"level_expire_month" json:"levelExpireMonth"` // 级别到期日期月
	LevelExpireDay   int         `orm:"level_expire_day"   json:"levelExpireDay"`   // 级别到期日期日
	LastLoginAt      int         `orm:"last_login_at"      json:"lastLoginAt"`      // 最后一次登录时间
	IsBan            int         `orm:"is_ban"             json:"isBan"`            // 是否被禁用
	CreatedAt        int         `orm:"created_at"         json:"createdAt"`        // 创建时间
	UpdatedAt        int         `orm:"updated_at"         json:"updatedAt"`        // 更新时间
}
