// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// UserSensitiveWord is the golang structure for table c_user_sensitive_word.
type UserSensitiveWord struct {
	Id             int64  `orm:"id,primary"      json:"id"`             // ID
	UserId         int64  `orm:"user_id"         json:"userId"`         // 会员ID
	Type           int    `orm:"type"            json:"type"`           // 类型: 1对话 2用户名
	TopicType      int    `orm:"topic_type"      json:"topicType"`      // 对话类型: 0无 1gpt3 2gpt4 3mj
	Content        string `orm:"content"         json:"content"`        // 触发敏感词原文
	ValidateResult string `orm:"validate_result" json:"validateResult"` // 敏感词json
	CreatedAt      int    `orm:"created_at"      json:"createdAt"`      // 创建时间
}
