// Copyright 2023 Anlity <leo@leocode.net>. All rights reserved.
// Use of this source code is governed by a AGPL v3.0 style
// license that can be found in the LICENSE file.

// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// UserInfo is the golang structure for table c_user_info.
type UserInfo struct {
	UserId   int64  `orm:"user_id,primary" json:"userId"`   // ID
	Nickname string `orm:"nickname"        json:"nickname"` // 昵称
	Avatar   string `orm:"avatar"          json:"avatar"`   // 头像
}
