// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package entity

import (
	"github.com/anlityli/chatait-free/chatait-public-lib/app/model/entity/internal"
)

// ConfigBaidu is the golang structure for table c_config_baidu.
type ConfigBaidu internal.ConfigBaidu

// Fill with you ideas below.
