// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package entity

import (
	"github.com/anlityli/chatait-free/chatait-public-lib/app/model/entity/internal"
)

// ConfigSensitiveWord is the golang structure for table c_config_sensitive_word.
type ConfigSensitiveWord internal.ConfigSensitiveWord

// Fill with you ideas below.
