// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package entity

import (
	"github.com/anlityli/chatait-free/chatait-public-lib/app/model/entity/internal"
)

// UserSensitiveWord is the golang structure for table c_user_sensitive_word.
type UserSensitiveWord internal.UserSensitiveWord

// Fill with you ideas below.
