// Copyright 2023 Anlity <leo@leocode.net>. All rights reserved.
// Use of this source code is governed by a AGPL v3.0 style
// license that can be found in the LICENSE file.

// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package entity

import (
	"github.com/anlityli/chatait-free/chatait-public-lib/app/model/entity/internal"
)

// UserInfo is the golang structure for table c_user_info.
type UserInfo internal.UserInfo

// Fill with you ideas below.
